spring.application.name=PVH_GROUP_03_SPRING_MINI_PROJECT

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_project
spring.datasource.username=postgres
spring.datasource.password=Admin

spring.mail.username=makaramouk@gmail.com
spring.mail.password=cemo npxa tomd xhvd
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.servlet.multipart.max-file-size=100MB

# RustFS S3 Configuration
rustfs.url=http://localhost:9000
rustfs.access.name=${RUSTFS_ACCESS_KEY:ZLMWxH2ppFSzkb6Pdhra}
rustfs.access.secret=${RUSTFS_SECRET_KEY:qyngphOdkZA540keiZWJm3tJ66LcBTomkYkxckQ3}
rustfs.bucket.name=group03